### PR TITLE
Intermediary PR

### PR DESCRIPTION
**Pull request by NormannR**
Just to take a peek!

### CODE REVIEW

**Comment by albop** [comment]
This is the branch fixing the bugs in main, right ? It's not where you add aggregate states and controls is it ?
If so, we could try to merge it before adding the new functionalities.

**Comment by NormannR** [comment]
Exactly: bugs are the only things addressed so far. I would prefer to do some more cleaning before merging it, if you don't mind.

**Comment by albop** [comment]
Yes, sure, tell me when it's ready.

**Comment by albop** [comment]
Can I merge that one ?

**Pull request merged**
