### PR TITLE
Display information about HModel objects (Ref issue: #22)

### PR DESCRIPTION
**Pull request by NormannR**
Added methods __str__, __repr__ and _repr_html_ to the HModel class

### CODE REVIEW

**Comment by albop** [comment]
Thank you @NormannR . A quick question: line 119, the new version looks equivalent to the former one (`d.get(k, v)` is supposed to `d[k]` with default value `v` )
If it isn't that suggests a bug in the .get method. If I remember well, it is monkey patched by dolo, so that the structure returned by the yaml parsing behaves like a dict.

**Comment by NormannR** [comment]
It is not exactly equivalent, as `d.get()` returns a `ScalarNode` object in our case, and `ScalarNode` objects do not include any `get` method. We then return "Anonymous" if the attribute `value` does not exist within this ScalarNode object. If the `ScalarNode` object had a `get()` method, we could directly use the `get(k,v)` syntax as you suggest.

**Comment by albop** [comment]
Isn't `model.data`  rather a MappingNode object? From https://github.com/EconForge/dolang.py/blob/9e9d0a47c2558656b8ae33af379d2b66965985c2/dolang/yaml_tools.py#L44, I see that it is augmented with a .get method, as soon as dolang is loaded.
It's not devoid of problem though:
- it does not have a default value
- you when the key is present it returns a scalarvalue object, which implies further manipulation. And might justify to keep the try/except
So let's keep your version...

**Comment by albop** [comment]
Actually, would you mind reformatting your PR with black and commit the change ?

**Comment by NormannR** [comment]
> Isn't `model.data` rather a MappingNode object? From https://github.com/EconForge/dolang.py/blob/9e9d0a47c2558656b8ae33af379d2b66965985c2/dolang/yaml_tools.py#L44, I see that it is augmented with a .get method, as soon as dolang is loaded. It's not devoid of problem though:
> 
>     * it does not have a default value
> 
>     * you when the key is present it returns a scalarvalue object, which implies further manipulation. And might justify to keep the try/except
>       So let's keep your version...

Indeed, `model.data` is a `MappingNode` object and `model.data.name` is a `ScalarNode`object, but the latter does not have a `get` method from which one may get the `value` attribute that contains what we're looking for.

> Actually, would you mind reformatting your PR with black and commit the change ?

Right away!

**Pull request merged**
